# Generated by Django 2.0 on 2018-09-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Enter a term (e.g. Django)', max_length=40)),
                ('definition', models.CharField(help_text='Enter a definition (e.g. Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design)', max_length=250)),
            ],
        ),
    ]
